# Generated by Django 3.0.4 on 2020-03-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200308_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question.Answer'),
        ),
    ]
