# Generated by Django 3.0.4 on 2020-03-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200308_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='question.Answer'),
        ),
    ]
